<Project><ItemGroup Condition="'$(IncludeObsRuntime)' != 'false'"><Content Include="$(MSBuildThisFileDirectory)runtime/bin/64bit/*"><Link>%(Filename)%(Extension)</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory><CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory></Content><Content Include="$(MSBuildThisFileDirectory)runtime/data/**/*"><Link>runtime/data/%(RecursiveDir)%(Filename)%(Extension)</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory><CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory></Content><Content Include="$(MSBuildThisFileDirectory)runtime/obs-plugins/**/*"><Link>runtime/obs-plugins/%(RecursiveDir)%(Filename)%(Extension)</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory><CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory></Content></ItemGroup></Project>